### PR TITLE
add section for other maps

### PR DESCRIPTION
**Pull request by BoredGameGeek**
and link to no agenda meetups map

### CODE REVIEW

**Comment by bdougherty** [comment]
Didn't know about this, thanks!

**Comment by BoredGameGeek** [comment]
No problem. Thank you! Do you also run https://noagendahr.org ? Would appreciate a link under "Links"

**Comment by bdougherty** [comment]
@BoredGameGeek added

**Comment by BoredGameGeek** [comment]
Thanks much!

**Pull request merged**
